# @package _global_
# Inherit from base.yaml and override source/target dataset fields
defaults:
  - base.yaml

source:
  dataset: "dukemtmc"
  data_root: "/mnt/AIProjects/trinh/DATA/reid/DukeMTMC-reID"
  num_classes: 702

target:
  dataset: "msmt17"
  data_root: "/mnt/AIProjects/trinh/DATA/reid/MSMT17_V1"
